Replace print with loguru
AFM-SPM/topofileformats pull request #10
Opened 2023-11-10 13:27 UTC by SylviaWhittle

This PR replaces all the `print` statements with logging from `loguru` (colour coded too)

<img width="851" alt="image" src="https://github.com/AFM-SPM/topofileformats/assets/86117496/d0ee8427-a7d8-4f68-9e11-0f24ba1265ca">

2023-11-10 14:25 UTC, ns-rse requested changes
Quick and easy implementation. Some comments in-line.

2023-11-10 14:25 UTC, ns-rse commented on topofileformats/asd.py
> +logger.add(sys.stderr, format="<white>{time}</white> | <level>{level}</level> | <blue>{message}</blue>")
One of the things I like about `loguru` is the ability to include a `<color>{function}</color>` section in the format which helps with determining where within a package/module/sub-module/function logging is coming from, do you think it would be worth adding one in?

Don't mind on colour, `cyan` might be one option, I'd try and avoid `red` and `green` as they don't stand out for people who are colour blind.

2023-11-10 14:25 UTC, ns-rse commented on topofileformats/asd.py
>              f"created voltage converter. ad_range: {analogue_digital_range} -> {self.ad_range}, \
If lines are too long for linting I think you can avoid the need to escape line breaks with...

```suggestion
            f"created voltage converter. ad_range: {analogue_digital_range} -> {self.ad_range}, "
            "max voltage: {max_voltage}, scaling factor: {scaling_factor}, resolution: {resolution}"
```

Not sure one approach is inherently better than another though. :thinking:

2023-11-10 14:25 UTC, ns-rse commented on topofileformats/asd.py
> +        logger.info(f"header dict: \n{header_dict}")
Does the header dictionary need to be printed under `INFO` level or is it something that is more appropriate to `DEBUG`?

2023-11-10 14:25 UTC, ns-rse commented on topofileformats/asd.py
>                  f"WARNING: Resolution of image is different in x and y directions:\
Having `WARNING` in the log message when the level is `warning` seems redundant.

2023-11-10 14:25 UTC, ns-rse commented on topofileformats/asd.py
> +logger.add(sys.stderr, format="<white>{time}</white> | <level>{level}</level> | <blue>{message}</blue>")
I also pedantically think the main error message should be white, use colour on other sections but the log `message` are the thing we want to be able to read easiest and they stand out best in consoles when they are white.

2023-11-23 14:28 UTC, SylviaWhittle commented on topofileformats/asd.py
> +logger.add(sys.stderr, format="<white>{time}</white> | <level>{level}</level> | <blue>{message}</blue>")
How's this?
<img width="1089" alt="image" src="https://github.com/AFM-SPM/topofileformats/assets/86117496/e3207dc6-d990-40dc-b51d-8250a80894e3">

2023-11-23 16:10 UTC, SylviaWhittle commented on topofileformats/asd.py
>              f"created voltage converter. ad_range: {analogue_digital_range} -> {self.ad_range}, \
Done, thank you!

2023-11-27 11:15 UTC, ns-rse requested changes
Thanks for finding the time to continue working on this @SylviaWhittle .

I've one suggestion which is to setup the logger in `__init__.py` rather than its own file and noticed a very minor tidying to a couple of lines.

2023-11-27 11:15 UTC, ns-rse commented on topofileformats/logging.py
I would avoid having this as a separate file and importing it. Because its something that is required each time the package is initialised the logger can be setup in `__init__.py`, which from memory we do with TopoStats (I'm wondering if we should switch to `loguru` in TopoStats too :thinking: ).

2023-11-27 11:15 UTC, ns-rse commented on topofileformats/asd.py
> +            logger.info(f"Requested channel {channel} matches first channel in file: " f"{header_dict['channel1']}")
If this all fits on a single line of < 120 characters should only need a single string.

```suggestion
            logger.info(f"Requested channel {channel} matches first channel in file: {header_dict['channel1']}")
```

Ditto line 204.

2024-04-29 16:43 UTC, ns-rse approved these changes
This is good to go @SylviaWhittle :+1:

2024-04-29 16:44 UTC, merged