Add file type: SPM
AFM-SPM/topofileformats pull request #33
Opened 2024-04-22 14:34 UTC by SylviaWhittle

This PR adds SPM support.

Just basic loading of `.spm` files, akin to how I did `.asd`.

2024-04-24 06:25 UTC, ns-rse requested changes
Thanks @SylviaWhittle as with other PRs out some comments in-line.

Not sure what your plan is for integrating with TopoStats but we could likely use the "factory method" design pattern to select the correct loader based on file extensions.

2024-04-24 06:25 UTC, ns-rse commented on topofileformats/spm.py
> +        print(f"[{filename}] : Pixel size not found in metadata, defaulting to 1nm")
Perhaps...

```suggestion
        LOGGER.warning(f"[{filename}] : Pixel size not found in metadata, defaulting to 1nm")
```

2024-04-24 06:25 UTC, ns-rse commented on topofileformats/spm.py
> +    print(f"[{filename}] : Pixel to nm scaling : {pixel_to_nm_scaling}")
```suggestion
    LOGGER.info(f"[{filename}] : Pixel to nm scaling : {pixel_to_nm_scaling}")
```

2024-04-24 06:25 UTC, ns-rse commented on topofileformats/spm.py
> +    print(f"Loading image from : {file_path}")
This and others should probably be `LOGGER.[info|error|warning]()`

2024-04-24 06:25 UTC, ns-rse commented on topofileformats/spm.py
> +                # channel_description = channel.decode('latin1').split('"')[1] # incase the blank field raises quesions?
Looks like this is left over, is the blank field likely to be an issue?

2024-04-30 15:16 UTC, SylviaWhittle commented on pyproject.toml
>      "Programming Language :: Python :: 3.8",
Agree!

2024-04-30 15:20 UTC, SylviaWhittle commented on topofileformats/spm.py
> +                # channel_description = channel.decode('latin1').split('"')[1] # incase the blank field raises quesions?
I can't remember why I wrote this. I'll revert it back to how it is in topostats.

2024-05-01 07:10 UTC, ns-rse approved these changes
:+1: Good to go.

2024-05-01 08:55 UTC, merged