Adds pre-commit configuration (& markdownlint-cli2)
AFM-SPM/topofileformats pull request #6
Opened 2023-11-10 10:05 UTC by ns-rse

Closes #5

2023-11-10 12:53 UTC, SylviaWhittle requested changes
Thank you so much for looking over this repo and starting to bring it up to par with TopoStats. 😄 

Just one typo I noticed, sorry!

2023-11-10 12:53 UTC, SylviaWhittle commented on pyproject.toml
> +keywrods = [
```suggestion
keywords = [
```

2023-11-10 13:44 UTC, ns-rse commented on pyproject.toml
> +keywrods = [
Good catch thanks, my fingers were clearly not warmed up that early in the morning.

2023-11-11 21:44 UTC, SylviaWhittle approved these changes
Thank you 😄

2023-11-13 08:45 UTC, merged